export default function RootHead() {
  return (
    <>
      <title>Comment Section</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
